//APIs

export const AUTOCOMPLETE_PENDING = 'AUTOCOMPLETE_PENDING';
export const AUTOCOMPLETE_SUCCESS = 'AUTOCOMPLETE_SUCCESS';
export const AUTOCOMPLETE_ERROR = 'AUTOCOMPLETE_ERROR';

export const RECIPE_SEARCH_PENDING = 'RECIPE_SEARCH_PENDING';
export const RECIPE_SEARCH_SUCCESS = 'RECIPE_SEARCH_SUCCESS';
export const RECIPE_SEARCH_ERROR = 'RECIPE_SEARCH_ERROR';
export const RECIPE_SEARCH_EMPTY_SEARCH = 'RECIPE_SEARCH_EMPTY_SEARCH';
export const RECIPE_SEARCH_NO_RESULTS = 'RECIPE_SEARCH_NO_RESULTS'

export const SET_FAVORITES_CODES = 'SET_FAVORITES_CODES';
export const DELETE_FAVORITES_CODES = 'DELETE_FAVORITES_CODES';


// Database

export const RECIPE_ID = 'RECIPE_ID'

export const USER_FAVORITES_PENDING = 'USER_FAVORITES_PENDING';
export const USER_FAVORITES_SUCCESS = 'USER_FAVORITES_SUCCESS';
export const USER_FAVORITES_ERROR = 'USER_FAVORITES_ERROR';


// Form

export const SET_GENERAL_SEARCH = 'SET_GENERAL_SEARCH';

export const SET_CHIPS = 'SET_CHIPS'; 
export const DELETE_CHIP = 'DELETE_CHIP'; 
export const CLEAR_CHIPS = 'CLEAR_CHIP'; 

export const SET_SHOW_SLIDER_SELECTIONS_IN_CHIPS = 'SET_SHOW_SLIDER_SELECTIONS_IN_CHIPS';

export const SET_CUISINE = 'SET_CUISINE';
export const DELETE_CUISINE = 'DELETE_CUISINE';
export const CLEAR_CUISINE = 'CLEAR_CUISINE';

export const SET_DIET_TYPE = 'SET_DIET_TYPE';
export const DELETE_DIET_TYPE = 'DELETE_DIET_TYPE';
export const CLEAR_DIET_TYPE = 'CLEAR_DIET_TYPE';

export const SET_INGREDIENTS_LIST = 'SET_INGREDIENTS_LIST'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const CLEAR_INGREDIENTS_LIST = 'CLEAR_INGREDIENTS_LIST'

export const SET_INTOLERANCE = 'SET_INTOLERANCE';
export const DELETE_INTOLERANCE = 'DELETE_INTOLERANCE';
export const CLEAR_INTOLERANCE = 'CLEAR_INTOLERANCE';

export const SET_MAXIMUM_READY_TIME = 'SET_MAXIMUM_READY_TIME';
export const DELETE_MAXIMUM_READY_TIME = 'DELETE_MAXIMUM_READY_TIME';

export const SET_MEAL_TYPE = 'SET_MEAL_TYPE';
export const DELETE_MEAL_TYPE = 'DELETE_MEAL_TYPE';
export const CLEAR_MEAL_TYPE = 'CLEAR_MEAL_TYPE';

export const SET_SLIDERS = 'SET_SLIDERS';
export const DELETE_SLIDERS = 'DELETE_SLIDERS';


